const searchIndex = [
    { title: "Introduction", url: "introduction.html", tags: "start, basics, what is singularity" },
    { title: "Character Creation", url: "character_creation.html", tags: "step by step, hero, build" },
    { title: "Battle Encounters", url: "battle_encounters.html", tags: "combat, rules, fight, turn" },
    { title: "Ability Scores", url: "ability_scores.html", tags: "might, agility, endurance, wits, charm, skills" },
    { title: "Equipment", url: "equipment.html", tags: "gear, weapons, armor, items" },
    { title: "Talents", url: "character_creation/talents.html", tags: "feats, abilities, progression" },
    
    // Rules
    { title: "Actions", url: "battle_encounters/actions.html", tags: "combat actions, move, attack" },
    { title: "Statuses", url: "battle_encounters/statuses.html", tags: "conditions, blinded, prone" },
    { title: "Damage Types", url: "battle_encounters/damage_types.html", tags: "fire, cold, kinetic, resistance" },
    { title: "Wounds & Dying", url: "battle_encounters/wounds.html", tags: "death, injury, healing" },
    { title: "Wound Table", url: "battle_encounters/wound_table.html", tags: "injury, damage, body parts, critical, extreme wound" },
    { title: "Cover", url: "battle_encounters/cover.html", tags: "defense, obstacle, hide" },
    { title: "Size", url: "battle_encounters/size.html", tags: "scale, large, tiny, stealth" },
    { title: "Critical Hits", url: "battle_encounters/critical_hit.html", tags: "crit, double damage, extreme success" },
    
    // Powersets
    { title: "Bastion", url: "character_creation/powersets/bastion.html", tags: "tank, defense, shield" },
    { title: "Gadgeteer", url: "character_creation/powersets/gadgeteer.html", tags: "tech, devices, utility" },
    { title: "Marksman", url: "character_creation/powersets/marksman.html", tags: "ranged, sniper, gun" },
    { title: "Paragon", url: "character_creation/powersets/paragon.html", tags: "superman, flight, strength" },

    // Phenotypes
    { title: "Human", url: "character_creation/phenotypes/human.html", tags: "race, species, versatile" },
    { title: "Terran", url: "character_creation/phenotypes/subtypes/terran.html", tags: "human subtype, earth" },

    // Bastion Talents
    { title: "Bastion Talents", url: "character_creation/powersets/bastion/bastion_talents.html", tags: "bastion, talents, list, defense, tank" },
    { title: "Bastion's Resistance", url: "character_creation/powersets/bastion/bastion_talents/bastions_resistance.html", tags: "bastion talent, damage reduction, resistance" },
    { title: "Ironbound", url: "character_creation/powersets/bastion/bastion_talents/ironbound.html", tags: "bastion talent, hp, health, endurance" },
    { title: "Enlarged Presence", url: "character_creation/powersets/bastion/bastion_talents/enlarged_presence.html", tags: "bastion talent, size, large" },
    { title: "Protect the Weak", url: "character_creation/powersets/bastion/bastion_talents/protect_the_weak.html", tags: "bastion talent, defense, protection, penalty" },
    { title: "Defensive Stance", url: "character_creation/powersets/bastion/bastion_talents/defensive_stance.html", tags: "bastion talent, ac, defense, stance" },
    { title: "Increased Resistance", url: "character_creation/powersets/bastion/bastion_talents/increased_resistance.html", tags: "bastion talent, defense, resistance" },
    { title: "Intercept Attack", url: "character_creation/powersets/bastion/bastion_talents/intercept_attack.html", tags: "bastion talent, protection, ally, reaction" },
    { title: "Regenerative Fortitude", url: "character_creation/powersets/bastion/bastion_talents/regenerative_fortitude.html", tags: "bastion talent, healing, hp, regeneration" },
    { title: "Protective Barrier", url: "character_creation/powersets/bastion/bastion_talents/protective_barrier.html", tags: "bastion talent, ally, ac, aura" },
    { title: "Total Immunity", url: "character_creation/powersets/bastion/bastion_talents/total_immunity.html", tags: "bastion talent, immunity, defense" },
    { title: "Indomitable Will", url: "character_creation/powersets/bastion/bastion_talents/indomitable_will.html", tags: "bastion talent, saving throw, paralyzed, staggered, dazed" },
    { title: "Rapid Intercept", url: "character_creation/powersets/bastion/bastion_talents/rapid_intercept.html", tags: "bastion talent, protection, movement, intercept" },
    { title: "Adaptive Defense", url: "character_creation/powersets/bastion/bastion_talents/adaptive_defense.html", tags: "bastion talent, resistance, adaptive" },
    { title: "Legendary Resilience", url: "character_creation/powersets/bastion/bastion_talents/legendary_resilience.html", tags: "bastion talent, resistance, all damage" },
    { title: "Guardian Aura", url: "character_creation/powersets/bastion/bastion_talents/guardian_aura.html", tags: "bastion talent, ally, aura, resistance" },
    { title: "Immovable Object", url: "character_creation/powersets/bastion/bastion_talents/immovable_object.html", tags: "bastion talent, movement, prone, anchor" },
    { title: "Unbreakable", url: "character_creation/powersets/bastion/bastion_talents/unbreakable.html", tags: "bastion talent, unconscious, wound, survival" },
    
    // Marksman Talents
    { title: "Marksman Talents", url: "character_creation/powersets/marksman/marksman_talents.html", tags: "marksman, talents, list, ranged, shooter" },
    { title: "Deadeye", url: "character_creation/powersets/marksman/marksman_talents/deadeye.html", tags: "marksman talent, aim, accuracy" },
    { title: "Quickdraw", url: "character_creation/powersets/marksman/marksman_talents/quickdraw.html", tags: "marksman talent, initiative, draw weapon" },
    { title: "Suppressive Fire", url: "character_creation/powersets/marksman/marksman_talents/suppressive_fire.html", tags: "marksman talent, area, control" },
    { title: "Fast Reload", url: "character_creation/powersets/marksman/marksman_talents/fast_reload.html", tags: "marksman talent, reload, speed" },
    { title: "Stabilized Movement", url: "character_creation/powersets/marksman/marksman_talents/stabilized_movement.html", tags: "marksman talent, movement, deadeye" },
    { title: "Surgical Precision", url: "character_creation/powersets/marksman/marksman_talents/surgical_precision.html", tags: "marksman talent, wound, precision" },
    { title: "Improved Deadeye", url: "character_creation/powersets/marksman/marksman_talents/improved_deadeye.html", tags: "marksman talent, aim, accuracy, deadeye" },
    { title: "Trick Shot", url: "character_creation/powersets/marksman/marksman_talents/trick_shot.html", tags: "marksman talent, special ammo, status effects, utility" },
    { title: "Rapid Fire", url: "character_creation/powersets/marksman/marksman_talents/rapid_fire.html", tags: "marksman talent, multiple attacks, damage" },
    { title: "Specialized Ammunition", url: "character_creation/powersets/marksman/marksman_talents/specialized_ammunition.html", tags: "marksman talent, damage type, fire, cold, electricity" },
    { title: "Tripoint Trauma", url: "character_creation/powersets/marksman/marksman_talents/tripoint_trauma.html", tags: "marksman talent, critical, wound" },
    { title: "Lightning Reload", url: "character_creation/powersets/marksman/marksman_talents/lightning_reload.html", tags: "marksman talent, reload, fast reload, agility" },
    { title: "Perfect Aim", url: "character_creation/powersets/marksman/marksman_talents/perfect_aim.html", tags: "marksman talent, aim, cover, deadeye" },
    { title: "Penetrating Shot", url: "character_creation/powersets/marksman/marksman_talents/penetrating_shot.html", tags: "marksman talent, cover, perfect aim, ignore cover" },
    { title: "Ricochet Shot", url: "character_creation/powersets/marksman/marksman_talents/ricochet_shot.html", tags: "marksman talent, utility, cover, positioning" },
    { title: "Master Marksman", url: "character_creation/powersets/marksman/marksman_talents/master_marksman.html", tags: "marksman talent, damage, bonus" },
    { title: "Master Ricochet", url: "character_creation/powersets/marksman/marksman_talents/master_ricochet.html", tags: "marksman talent, ricochet shot, penalty, accuracy" },
    { title: "Pinpoint Accuracy", url: "character_creation/powersets/marksman/marksman_talents/pinpoint_accuracy.html", tags: "marksman talent, critical hit, precision" },
    { title: "Versatile Arsenal", url: "character_creation/powersets/marksman/marksman_talents/versatile_arsenal.html", tags: "marksman talent, weapons, versatility" },
    { title: "Deadly Focus", url: "character_creation/powersets/marksman/marksman_talents/deadly_focus.html", tags: "marksman talent, damage, deadeye, double damage" },
    { title: "Enhanced Precision", url: "character_creation/powersets/marksman/marksman_talents/enhanced_precision.html", tags: "marksman talent, deadeye, bonus, accuracy" },
    { title: "Impossible Shot", url: "character_creation/powersets/marksman/marksman_talents/impossible_shot.html", tags: "marksman talent, utility, range, cover" },
    { title: "Unerring Aim", url: "character_creation/powersets/marksman/marksman_talents/unerring_aim.html", tags: "marksman talent, aim, accuracy, perfect aim" },
    { title: "Perfect Shot", url: "character_creation/powersets/marksman/marksman_talents/perfect_shot.html", tags: "marksman talent, ultimate, auto hit, critical" },
    { title: "Blast", url: "character_creation/talents/blast_apprentice.html", tags: "generic talent, attack, damage, energy" },
    { title: "Generic Talent", url: "character_creation/talents.html", tags: "talents, list, feats, progression" },

    // History & Lore
    { title: "History of Humanity", url: "../history_of_humanity/history_of_humanity.html", tags: "lore, timeline, world, setting" },
    { title: "Before the First Contact", url: "../history_of_humanity/chapters/before_the_fc.html", tags: "history, chapter 1, old earth" },
    { title: "The First Contact", url: "../history_of_humanity/chapters/first_contact.html", tags: "history, chapter 2, strangers, singularium" },
    { title: "The Age of Advancement", url: "../history_of_humanity/chapters/age_of_advancement.html", tags: "history, chapter 3, golden age" },
    { title: "The Age of Division", url: "../history_of_humanity/chapters/age_of_division.html", tags: "history, chapter 4, war, conflict" },
    { title: "Power Blocs & Organizations", url: "../history_of_humanity/chapters/nations&powerblocs.html", tags: "history, chapter 5, politics, factions" },
    { title: "The Free States of Terra", url: "../history_of_humanity/chapters/powerblocs/free_states_of_terra.html", tags: "faction, fst, democracy, corporation" },
    { title: "Grand Principality of Varysk", url: "../history_of_humanity/chapters/powerblocs/varysk.html", tags: "faction, varysk, iron, anti-tech" },
    { title: "The Church of Singularity", url: "../history_of_humanity/chapters/organizations/church_of_singularity.html", tags: "faction, religion, tech, research" },

    // Minions & Villains
    { title: "Minions & Villains", url: "../minions&villains/minions&villains.html", tags: "enemies, npcs, monsters, bestiary" },
    { title: "Thug", url: "../minions&villains/minions/thug.html", tags: "enemy, minion, criminal, low level" },
    { title: "Soldier", url: "../minions&villains/minions/soldier.html", tags: "enemy, minion, military, guard" },

    // Backgrounds
    { title: "Backgrounds", url: "character_creation/backgrounds.html", tags: "origin, backstory, skills" },
    { title: "Athlete", url: "character_creation/backgrounds/athlete.html", tags: "background, physical, sports" },
    { title: "Criminal", url: "character_creation/backgrounds/criminal.html", tags: "background, stealth, underworld" },
    { title: "Journalist", url: "character_creation/backgrounds/journalist.html", tags: "background, social, investigation" },
    { title: "Tech Enthusiast", url: "character_creation/backgrounds/tech_enthusiast.html", tags: "background, computers, hacking" },

    // Gadgets (Gadgeteer)
    { title: "Gadgets", url: "character_creation/powersets/gadgeteer/gadgets.html", tags: "tech, items, devices" },
    { title: "Liquid Foam Spray", url: "character_creation/powersets/gadgeteer/gadgets/liquid_foam_spray.html", tags: "gadget, crowd control, difficult terrain" },
    { title: "Magnetic Grapnel", url: "character_creation/powersets/gadgeteer/gadgets/magnetic_grapnel.html", tags: "gadget, movement, grapple" },
    { title: "Micro-Missile Launcher", url: "character_creation/powersets/gadgeteer/gadgets/micro_missile_launcher.html", tags: "gadget, attack, fire" },
    { title: "Photon Projector", url: "character_creation/powersets/gadgeteer/gadgets/photon_projector.html", tags: "gadget, light, utility" },
    { title: "Support Drone", url: "character_creation/powersets/gadgeteer/gadgets/support_drone.html", tags: "gadget, buff, ally" },
    { title: "Remote Med-Siphon", url: "character_creation/powersets/gadgeteer/gadgets/remote_med_siphon.html", tags: "gadget, healing, range" },
    { title: "Sonic Grenade", url: "character_creation/powersets/gadgeteer/gadgets/sonic_grenade.html", tags: "gadget, aoe, stun, daze" },
    { title: "Trauma Stabilizer", url: "character_creation/powersets/gadgeteer/gadgets/trauma_stabilizer.html", tags: "gadget, healing, touch" },
    { title: "Adrenaline Injector", url: "character_creation/powersets/gadgeteer/gadgets/adrenaline_injector.html", tags: "gadget, buff, speed, attack, saving throw, fatigued" },
    { title: "Enough Prep Time", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/enough_prep_time.html", tags: "gadgeteer talent, planning, bonus" },
    { title: "Expanded Loadout", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/expanded_loadout.html", tags: "gadgeteer talent, slots, preparation" },
    { title: "Improvised Gadget", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/improvised_gadget.html", tags: "gadgeteer talent, create, random" },
    { title: "Multiple Preparations", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/multiple_preparations.html", tags: "gadgeteer talent, preparation, multiple enemies" },
    { title: "Rapid Preparation", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/rapid_preparation.html", tags: "gadgeteer talent, preparation, time reduction" },
    { title: "Superior Engineering", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/superior_engineering.html", tags: "gadgeteer talent, gadget mastery, engineering" },
    { title: "Sustained Tuning", url: "character_creation/powersets/gadgeteer/gadgeteer_talents/sustained_tuning.html", tags: "gadgeteer talent, gadget tuning, maintain, dc" },

    // Paragon Talents
    { title: "Dominating Presence", url: "character_creation/powersets/paragon/paragon_talents/dominating_presence.html", tags: "paragon talent, intimidation, flight" },
    { title: "Impact Control", url: "character_creation/powersets/paragon/paragon_talents/impact_control.html", tags: "paragon talent, fall damage, resistance" },
    { title: "Noble Presence", url: "character_creation/powersets/paragon/paragon_talents/noble_presence.html", tags: "paragon talent, persuasion, flight" },
    { title: "Supersonic Moment", url: "character_creation/powersets/paragon/paragon_talents/supersonic_moment.html", tags: "paragon talent, damage, flight, speed, melee" },
    { title: "Meteor Slam", url: "character_creation/powersets/paragon/paragon_talents/meteor_slam.html", tags: "paragon talent, flight, slam, prone, falling damage" },

    // Generic Talents
    { title: "Armor Training", url: "character_creation/talents.html", tags: "light, medium, heavy, armor proficiency" },
    { title: "Weapon Training", url: "character_creation/talents.html", tags: "apprentice, competent, masterful, legendary, weapon proficiency" },
    { title: "Saving Throw Training", url: "character_creation/talents.html", tags: "apprentice, competent, masterful, legendary, saves" },
    { title: "Skill Training", url: "character_creation/talents.html", tags: "apprentice, competent, masterful, legendary, skills" },
    { title: "Hard to Kill", url: "character_creation/talents/hard_to_kill.html", tags: "generic talent, health, wounds, death" },
    { title: "Enhanced Vitality", url: "character_creation/talents/enhanced_vitality.html", tags: "talent, enhanced vitality, hp, hit points, resilience" },
    { title: "Public Image I", url: "character_creation/talents/public_image_i.html", tags: "talent, public image, charm, social, civilians, reputation" },
    { title: "Public Image II", url: "character_creation/talents/public_image_ii.html", tags: "talent, public image, charm, social, civilians, reputation, influence" },
    { title: "Public Image III", url: "character_creation/talents/public_image_iii.html", tags: "talent, public image, charm, social, civilians, reputation, legendary, masses" },
    { title: "Public Image IV", url: "character_creation/talents/public_image_iv.html", tags: "talent, public image, charm, social, civilians, reputation, icon, legend" },
    { title: "Public Image V", url: "character_creation/talents/public_image_v.html", tags: "talent, public image, charm, social, civilians, reputation, legend, force, legendary" },
    { title: "Initiative Training", url: "character_creation/talents/initiative_training_apprentice.html", tags: "generic talent, speed, reaction" },
    { title: "Marine Training", url: "character_creation/talents/marine_training.html", tags: "generic talent, water, aquatic, swimming" },
    { title: "Swift Runner", url: "character_creation/talents/swift_runner.html", tags: "generic talent, speed, movement" },

    // Actions & Statuses
    { title: "Analyze", url: "battle_encounters/actions/analyze.html", tags: "action, wits, investigate" },
    { title: "Attack", url: "battle_encounters/actions/attack.html", tags: "action, combat, strike" },
    { title: "Brace", url: "battle_encounters/actions/brace.html", tags: "action, defense, ac" },
    { title: "Draw", url: "battle_encounters/actions/draw.html", tags: "action, equip, item" },
    { title: "Drop", url: "battle_encounters/actions/drop.html", tags: "action, free, item" },
    { title: "Healing", url: "battle_encounters/actions/healing.html", tags: "action, heal, hp, medical, medicine" },
    { title: "Intimidate", url: "battle_encounters/actions/intimidate.html", tags: "action, intimidation, charm, scared, fear, social" },
    { title: "Move", url: "battle_encounters/actions/move.html", tags: "action, movement, speed" },
    { title: "Reposition", url: "battle_encounters/actions/reposition.html", tags: "action, shove, push" },
    { title: "Stand Up", url: "battle_encounters/actions/standup.html", tags: "action, prone, get up" },
    { title: "Step", url: "battle_encounters/actions/step.html", tags: "action, movement, shift" },
    { title: "Stow", url: "battle_encounters/actions/stow.html", tags: "action, inventory, hide" },
    { title: "Trip", url: "battle_encounters/actions/trip.html", tags: "action, knock down, prone" },
    { title: "Blinded", url: "battle_encounters/statuses/blinded.html", tags: "status, condition, sight" },
    { title: "Dazed", url: "battle_encounters/statuses/dazed.html", tags: "status, condition, reaction" },
    { title: "Deafened", url: "battle_encounters/statuses/deafened.html", tags: "status, condition, hearing" },
    { title: "Fatigued", url: "battle_encounters/statuses/fatigued.html", tags: "status, condition, tired, exhaustion" },
    { title: "Immobilized", url: "battle_encounters/statuses/immobilized.html", tags: "status, condition, movement, restrained" },
    { title: "Incorporeal", url: "battle_encounters/statuses/incorporeal.html", tags: "status, condition, ethereal, ghost" },
    { title: "Off-balance", url: "battle_encounters/statuses/offbalance.html", tags: "status, condition, ac penalty" },
    { title: "Prone", url: "battle_encounters/statuses/prone.html", tags: "status, condition, ground" },
    { title: "Scared", url: "battle_encounters/statuses/scared.html", tags: "status, condition, fear, frightened" },
    { title: "Staggered", url: "battle_encounters/statuses/staggered.html", tags: "status, condition, energy" },
    { title: "Stunned", url: "battle_encounters/statuses/stunned.html", tags: "status, condition, actions, reactions" },
    { title: "Untrained Armor", url: "battle_encounters/untrained_armor.html", tags: "rules, penalty, ac" },
    { title: "Repeated Attack Penalty", url: "battle_encounters/repeated_attack_penalty.html", tags: "rules, rap, multiattack" },
    { title: "Restricted Ranged Combat", url: "battle_encounters/restricted_ranged_combat.html", tags: "rules, flying, climbing, shooting" },
    { title: "Spark", url: "battle_encounters/spark.html", tags: "rules, hero point, reroll, inspiration" },
    { title: "Disengaging", url: "battle_encounters/disengaging_from_melee.html", tags: "rules, movement, retreat" },

    // Equipment
    { title: "Combat Knife", url: "equipment/weapons/combat_knife.html", tags: "weapon, melee, light" },
    { title: "Greatsword", url: "equipment/weapons/greatsword.html", tags: "weapon, melee, heavy, two-handed" },
    { title: "Pistol", url: "equipment/weapons/pistol.html", tags: "weapon, ranged, firearm" },
    { title: "Rifle", url: "equipment/weapons/rifle.html", tags: "weapon, ranged, firearm, long range" },
    { title: "Short Bow", url: "equipment/weapons/short_bow.html", tags: "weapon, ranged, bow" },
    { title: "Shortsword", url: "equipment/weapons/shortsword.html", tags: "weapon, melee" },
    { title: "Unarmed Strike", url: "equipment/weapons/unarmed_strike.html", tags: "weapon, melee, fist" },
    { title: "Jacket", url: "equipment/armors/jacket.html", tags: "armor, light" },
    { title: "Combat Vest", url: "equipment/armors/combat_vest.html", tags: "armor, medium" },
    { title: "Plated Assault Armor", url: "equipment/armors/plated_assault_armor.html", tags: "armor, heavy" },
    { title: "Weapon Traits", url: "equipment/weapon_traits.html", tags: "rules, equipment, properties" },
    { title: "Armor Traits", url: "equipment/armor_traits.html", tags: "rules, equipment, properties" },
    { title: "Noisy", url: "equipment/armor_traits/noisy.html", tags: "armor trait, noise, stealth penalty" },

    // Consumables
    { title: "Consumables", url: "equipment/consumable.html", tags: "items, single-use, temporary, effects" },
    { title: "Underwater Breathing Gel", url: "equipment/consumables/underwater_breathing_gel.html", tags: "consumable, water, breathing, aquatic" },
    { title: "Glow Stick", url: "equipment/consumables/glow_stick.html", tags: "consumable, light, illumination, torch" },
    { title: "Med-Gel I", url: "equipment/consumables/med_gel_i.html", tags: "consumable, healing, hp, medical" },
    { title: "Med-Gel II", url: "equipment/consumables/med_gel_ii.html", tags: "consumable, healing, hp, medical" },
    { title: "Med-Gel III", url: "equipment/consumables/med_gel_iii.html", tags: "consumable, healing, hp, medical" },
    { title: "Med-Gel IV", url: "equipment/consumables/med_gel_iv.html", tags: "consumable, healing, hp, medical" },
    { title: "Med-Gel V", url: "equipment/consumables/med_gel_v.html", tags: "consumable, healing, hp, medical" },
    { title: "Med-Gel VI", url: "equipment/consumables/med_gel_vi.html", tags: "consumable, healing, hp, medical" },

    // Weapon Modifications
    { title: "Weapon Modifications", url: "equipment/weapon_modifications.html", tags: "equipment, upgrade, enhance, list" },
    { title: "Damage Type Conversion", url: "equipment/modifications/weapon_modifications/damage_type_conversion.html", tags: "weapon mod, damage type, change" },
    { title: "Damage Enhancement I", url: "equipment/modifications/weapon_modifications/damage_enhancement_i.html", tags: "weapon mod, damage bonus, dice" },
    { title: "Damage Enhancement II", url: "equipment/modifications/weapon_modifications/damage_enhancement_ii.html", tags: "weapon mod, damage bonus, dice" },
    { title: "Damage Enhancement III", url: "equipment/modifications/weapon_modifications/damage_enhancement_iii.html", tags: "weapon mod, damage bonus, dice" },
    { title: "Damage Enhancement IV", url: "equipment/modifications/weapon_modifications/damage_enhancement_iv.html", tags: "weapon mod, damage bonus, dice" },

    // Armor Modifications
    { title: "Armor Modifications", url: "equipment/armor_modifications.html", tags: "equipment, upgrade, enhance, list" },
    { title: "Armor Enhancement I", url: "equipment/modifications/armor_modifications/armor_enhancement_i.html", tags: "armor mod, ac bonus, defense" },
    { title: "Armor Enhancement II", url: "equipment/modifications/armor_modifications/armor_enhancement_ii.html", tags: "armor mod, ac bonus, defense" },
    { title: "Armor Enhancement III", url: "equipment/modifications/armor_modifications/armor_enhancement_iii.html", tags: "armor mod, ac bonus, defense" },
    { title: "Armor Enhancement IV", url: "equipment/modifications/armor_modifications/armor_enhancement_iv.html", tags: "armor mod, ac bonus, defense" },
    { title: "Resistance Enhancement I", url: "equipment/modifications/armor_modifications/resistance_enhancement_i.html", tags: "armor mod, damage resistance, defense" },
    { title: "Resistance Enhancement II", url: "equipment/modifications/armor_modifications/resistance_enhancement_ii.html", tags: "armor mod, damage resistance, defense" },
    { title: "Resistance Enhancement III", url: "equipment/modifications/armor_modifications/resistance_enhancement_iii.html", tags: "armor mod, damage resistance, defense" },
    { title: "Resistance Enhancement IV", url: "equipment/modifications/armor_modifications/resistance_enhancement_iv.html", tags: "armor mod, damage resistance, defense" },
    { title: "Silence Enhancement I", url: "equipment/modifications/armor_modifications/silence_enhancement_i.html", tags: "armor mod, stealth, noisy, quiet" },
    { title: "Silence Enhancement II", url: "equipment/modifications/armor_modifications/silence_enhancement_ii.html", tags: "armor mod, stealth, noisy, quiet" },
    { title: "Silence Enhancement III", url: "equipment/modifications/armor_modifications/silence_enhancement_iii.html", tags: "armor mod, stealth, noisy, quiet" },
    { title: "Silence Enhancement IV", url: "equipment/modifications/armor_modifications/silence_enhancement_iv.html", tags: "armor mod, stealth, noisy, quiet" },
    { title: "Silence Enhancement V", url: "equipment/modifications/armor_modifications/silence_enhancement_v.html", tags: "armor mod, stealth, noisy, quiet" },
    { title: "Safeguard Enhancement I", url: "equipment/modifications/armor_modifications/safeguard_enhancement_i.html", tags: "armor mod, saving throw, bonus, resilience" },
    { title: "Safeguard Enhancement II", url: "equipment/modifications/armor_modifications/safeguard_enhancement_ii.html", tags: "armor mod, saving throw, bonus, resilience" },
    { title: "Safeguard Enhancement III", url: "equipment/modifications/armor_modifications/safeguard_enhancement_iii.html", tags: "armor mod, saving throw, bonus, resilience" },
    { title: "Safeguard Enhancement IV", url: "equipment/modifications/armor_modifications/safeguard_enhancement_iv.html", tags: "armor mod, saving throw, bonus, resilience" },
    { title: "Safeguard Enhancement V", url: "equipment/modifications/armor_modifications/safeguard_enhancement_v.html", tags: "armor mod, saving throw, bonus, resilience" }
];